#!/usr/bin/env python3
"""Counter — generated by `plexi app init`.

Dev loop: `just dev` (open + hot reload) · `just health` (validate) · `just lint`
UI API: read `plexi_sdk/ui.py` | Publish: uncomment [marketplace] in manifest.toml
"""
from plexi_sdk import App
from plexi_sdk.ui import AppBar, Column, FooterKeys, Label, Spacer


class Counter(App):
    def on_init(self) -> None:
        self.count: int = self.state.get("count", 0)

    def view(self):
        return Column([
            AppBar(title="Counter"),
            Label(str(self.count), bold=True),
            Spacer(grow=True),
            FooterKeys(shortcuts=[
                ("+", "increment"),
                ("-", "decrement"),
                ("r", "reset"),
            ]),
        ])

    def on_key(self, key: str, mods: dict) -> None:
        if key in ("equals", "plus"):
            self.count += 1
        elif key == "minus":
            self.count -= 1
        elif key == "r":
            self.count = 0
        self.state.save({"count": self.count})
        self.emit.schedule_render()


Counter().run()
