#!/usr/bin/env python3
"""__DISPLAY_NAME__ — agent app generated by `plexi app init --agent`. Edit main.py to build your agent."""
from plexi_sdk import App, RenderContext
from plexi_sdk.ui import AppBar, Card, Column, FooterKeys, Label, TextEdit


class __CLASS_NAME__(App):
    async def on_init(self, ctx: RenderContext) -> None:
        self._messages: list[dict] = []
        self._input = TextEdit(placeholder="Type a message and press Enter…")
        self.emit.info("__DISPLAY_NAME__ initialized")

    def on_render(self, ctx: RenderContext) -> None:
        message_labels = [
            Label(f"{'you' if m['role'] == 'user' else 'agent'}: {m['content']}")
            for m in self._messages
        ]
        ctx.render(Column([
            AppBar(title="__DISPLAY_NAME__", subtitle="ai.query agent"),
            *message_labels,
            Card([self._input]),
            FooterKeys([("enter", "send"), ("esc", "close")]),
        ]))

    def on_key(self, ctx: RenderContext, key: str, _mods: dict) -> None:
        if key == "escape":
            self.emit.close_self()
            return
        if key == "return":
            text = self._input.value.strip()
            if not text:
                return
            self._messages.append({"role": "user", "content": text})
            self._input.value = ""
            ctx.request_frame()
            self._send_query(ctx, text)

    def _send_query(self, ctx: RenderContext, text: str) -> None:
        try:
            result = ctx.ai_query(text)
            self._messages.append({"role": "agent", "content": result})
        except Exception as e:
            self._messages.append({"role": "agent", "content": f"error: {e}"})
            self.emit.error(f"ai_query failed: {e}")
        ctx.request_frame()


__CLASS_NAME__().run()
