#!/usr/bin/env python3
"""__DISPLAY_NAME__ — agent app generated by `plexi agent init`. Edit main.py to build your agent."""
import threading
from plexi_sdk import App, RenderContext
from plexi_sdk.ui import AppBar, Card, Column, FooterKeys, Label, TextInput


class __CLASS_NAME__(App):
    async def on_init(self) -> None:
        self._messages: list[dict] = []
        self._input = TextInput("input", placeholder="Type a message and press Enter…")
        self.emit.info("__DISPLAY_NAME__ initialized")

    def on_render(self, ctx: RenderContext) -> None:
        message_labels = [
            Label(f"{'you' if m['role'] == 'user' else 'agent'}: {m['content']}")
            for m in self._messages
        ]
        ctx.render(Column([
            AppBar(title="__DISPLAY_NAME__", subtitle="ai.query agent"),
            *message_labels,
            Card([self._input]),
            FooterKeys([("enter", "send"), ("esc", "close")]),
        ]))
        if self._input.submitted:
            text = self._input.submitted.strip()
            if text:
                self._messages.append({"role": "user", "content": text})
                threading.Thread(target=self._send_query, args=(text,), daemon=True).start()

    def on_key(self, key: str, _mods: dict) -> None:
        if key == "escape":
            self.emit.close_self()

    def _send_query(self, text: str) -> None:
        try:
            response = self.emit.run_sync(self.emit.ai_query(
                model_tier="low",
                system="You are a helpful assistant.",
                messages=[{"role": "user", "content": text}],
            ))
            self._messages.append({"role": "agent", "content": response.content})
        except Exception as e:
            self._messages.append({"role": "agent", "content": f"error: {e}"})
            self.emit.error(f"ai_query failed: {e}")
        self.emit.schedule_render()


__CLASS_NAME__().run()
