#!/usr/bin/env python3
"""__DISPLAY_NAME__ - agent app generated by `plexi agent init`."""

from plexi_sdk import state
from plexi_sdk.effects import AiMessage, AiQuery, CloseSelf, SetState, SetStatus, SetTitle
from plexi_sdk.events import AiResponse, KeyEvent, UiAction, UiValueChange
from plexi_sdk.ui import AppBar, Card, Column, Component, FooterKeys, Text, TextEdit


REQUEST_ID = "agent-query"


def init(size, args):
    return [
        SetTitle("__DISPLAY_NAME__"),
        SetState({"messages": [], "draft": "", "waiting": False}),
        SetStatus("Ready"),
    ]


def update(event):
    data = state.all()

    if isinstance(event, UiValueChange) and event.handler_id == "agent-input":
        data["draft"] = event.value
        return [SetState(data)]

    if isinstance(event, UiAction) and event.handler_id == "agent-input":
        text = str(data.get("draft", "")).strip()
        if not text or data.get("waiting"):
            return []
        messages = list(data.get("messages", []))
        messages.append({"role": "user", "content": text})
        data.update({"messages": messages, "draft": "", "waiting": True})
        return [
            SetState(data),
            SetStatus("Asking"),
            AiQuery(
                request_id=REQUEST_ID,
                model_tier="low",
                system="You are a helpful assistant.",
                messages=[AiMessage(role="user", content=text)],
            ),
        ]

    if isinstance(event, AiResponse) and event.request_id == REQUEST_ID:
        messages = list(data.get("messages", []))
        content = event.content if event.content is not None else f"error: {event.error}"
        messages.append({"role": "agent", "content": content or ""})
        data.update({"messages": messages, "waiting": False})
        return [SetState(data), SetStatus("Ready")]

    if isinstance(event, KeyEvent) and event.pressed and event.key == "escape":
        return [CloseSelf()]

    return []


def view():
    messages = list(state.get("messages", []))
    draft = str(state.get("draft", ""))
    waiting = bool(state.get("waiting", False))
    rows: list[Component] = [
        Text(f"{m.get('role', 'agent')}: {m.get('content', '')}")
        for m in messages[-12:]
        if isinstance(m, dict)
    ]
    if waiting:
        rows.append(Text("agent: ...", tone="hint"))
    return Column([
        AppBar(title="__DISPLAY_NAME__", subtitle="ai.query agent"),
        Card(rows or [Text("No messages yet.", tone="hint")]),
        TextEdit("agent-input", value=draft, placeholder="Type a message and press Enter"),
        FooterKeys([("enter", "send"), ("esc", "close")]),
    ], grow=True)
