#!/usr/bin/env python3
"""
__DISPLAY_NAME__ — generated by `plexi app init`.

Delete what you don't need.
"""
from plexi_sdk import App, RenderContext
from plexi_sdk.ui import (
    AppBar,
    ButtonRow,
    Card,
    Column,
    FooterKeys,
    InfoTable,
    KeyRow,
    Label,
    Section,
    Spacer,
)


class __CLASS_NAME__(App):
    async def on_init(self, ctx: RenderContext) -> None:
        state = ctx.load_state()
        self.click_count = state.get("clicks", 0)
        self._btn = ButtonRow("action", "Click me")
        ctx.status_summary("Ready")
        self.emit.info("__DISPLAY_NAME__ initialized")

    def on_render(self, ctx: RenderContext) -> None:
        if self._btn.clicked:
            self.click_count += 1
            ctx.save_state({"clicks": self.click_count})
            ctx.status_summary(f"Clicked {self.click_count} time(s)")

        ctx.render(Column([
            AppBar(title="__DISPLAY_NAME__", subtitle="Edit main.py to build your app"),
            Section("APP INFO"),
            InfoTable([
                ("app_id", self.app_id),
                ("workspace", ctx.workspace_root or "(none)"),
                ("dimensions", f"{ctx.w:.0f} × {ctx.h:.0f}"),
                ("capabilities", ", ".join(ctx.capabilities) or "none"),
            ]),
            Section("ACTIONS"),
            Card([
                self._btn,
                Label(f"Clicks: {self.click_count}", color=ctx.theme.accent),
                Label(f"state stored in app_states/{self.app_id}.json — survives hot reload", tone="muted"),
            ]),
            Section("KEYBOARD SHORTCUTS"),
            Card([
                KeyRow("esc", "close"),
                KeyRow("i", "increment counter"),
            ]),
            Spacer(grow=True),
            FooterKeys([
                ("esc", "close"),
                ("i", "increment"),
            ]),
        ]))

    def on_key(self, ctx: RenderContext, key: str, _mods: dict) -> None:
        if key == "escape":
            self.emit.close_self()
        elif key == "i":
            self.click_count += 1
            ctx.save_state({"clicks": self.click_count})
            ctx.status_summary(f"Clicked {self.click_count} time(s)")

    # For async I/O (http, AI, secrets) make the handler async:
    # async def on_key(self, ctx: RenderContext, key: str, _mods: dict) -> None:
    #     result = await self.emit.http_get(url)  # non-blocking I/O


__CLASS_NAME__().run()
