#!/usr/bin/env python3
"""__DISPLAY_NAME__ — generated by `plexi app init`."""
from plexi_sdk import App, RenderContext
from plexi_sdk.ui import AppBar, Column, FooterKeys, Label, Spacer


class __CLASS_NAME__(App):
    async def on_init(self, ctx: RenderContext) -> None:
        state = ctx.load_state()
        self._count: int = state.get("count", 0)
        self._running = False

    def on_render(self, ctx: RenderContext) -> None:
        ctx.render(Column([
            AppBar(title="__DISPLAY_NAME__"),
            Spacer(24),
            Label(str(self._count), bold=True),
            Spacer(24),
            FooterKeys([
                ("space", "start/stop"),
                ("+/-", "increment"),
                ("r", "reset"),
                ("esc", "close"),
            ]),
        ]))

    async def on_key(self, ctx: RenderContext, key: str, mods: dict) -> None:
        if key in ("equal", "plus"):
            self._count += 1
        elif key in ("minus", "hyphen"):
            self._count -= 1
        elif key == "r":
            self._count = 0
        elif key == "space":
            if self._running:
                self.emit.cancel_timer("tick")
                self._running = False
            else:
                self.emit.set_timer("tick", 1000)
                self._running = True
        ctx.save_state({"count": self._count})

    async def on_timer(self, ctx: RenderContext, timer_id: str) -> None:
        if timer_id == "tick":
            self._count += 1
            ctx.save_state({"count": self._count})
            if self._running:
                self.emit.set_timer("tick", 1000)


__CLASS_NAME__().run()
