"""Tests for __DISPLAY_NAME__ — generated by `plexi app init`.

Run with:  plexi app test          (from the app directory)
       or:  uv run pytest tests/

AppHarness spawns this app as a real subprocess and speaks the PGAP protocol
over stdin/stdout — no running Plexi host or display required. See
`plexi_sdk/testing.py` for the full API (key injection, pixel asserts, …).
"""
from pathlib import Path

import pytest

from plexi_sdk.testing import AppHarness

APP = Path(__file__).resolve().parent.parent / "main.py"


@pytest.mark.parametrize("size", [(300, 200), (800, 600)])
def test_renders_without_overlap(size):
    """The view renders one frame with no overlapping rects, small and normal."""
    width, height = size
    # This exercises the same init -> update(RenderFrame) -> view lifecycle that
    # Plexi uses for a real app pane, then checks host-side layout geometry.
    with AppHarness(str(APP), width=width, height=height) as h:
        h.run(1)
        h.assert_no_overlap()


def test_snapshot(tmp_path):
    """Render a PNG snapshot of the first frame.

    Skips when the plexi binary is unavailable — snapshotting needs the host
    renderer, which is not present in a bare `uv run pytest` environment.
    """
    with AppHarness(str(APP), width=800, height=600) as h:
        h.run(1)
        try:
            h.save_snapshot(tmp_path / "snapshot.png")
        except RuntimeError as exc:
            pytest.skip(f"plexi binary not available for rendering: {exc}")
