"""Tests for __DISPLAY_NAME__ — generated by `plexi app init`.

Run with:  plexi app test          (from the app directory)
       or:  uv run --no-project --with pytest pytest tests/

AppHarness spawns this app as a real subprocess and speaks the PGAP protocol
over stdin/stdout — no running Plexi host or display required. See
`plexi_sdk/testing.py` for the full API (key injection, pixel asserts, …).
"""
import json
import shutil
from pathlib import Path

import pytest

from plexi_sdk.effects import ExposeTools, ToolResult
from plexi_sdk.events import ToolCall
from plexi_sdk.testing import AppHarness

APP_DIR = Path(__file__).resolve().parent.parent
APP = APP_DIR / "main.py"
if not APP.exists():
    # This template is collected as part of the SDK suite before `app init`
    # copies it into a generated app. Materialize the package layout under
    # their generated names and exercise them in a scratch directory.
    _TEMPLATES = Path(__file__).resolve().parent
    _SCRATCH = Path(__file__).resolve().parent / "__pycache__" / "scaffold_app"
    _SCRATCH.mkdir(parents=True, exist_ok=True)
    (_SCRATCH / "app").mkdir(exist_ok=True)
    (_SCRATCH / "app" / "__init__.py").touch()
    for _src, _dst in (
        ("app_init.py", "main.py"),
        ("app_init_tools.py", "app/tools.py"),
        ("app_init_ui.py", "app/ui.py"),
    ):
        shutil.copyfile(_TEMPLATES / _src, _SCRATCH / _dst)
    APP_DIR = _SCRATCH
    APP = _SCRATCH / "main.py"


@pytest.mark.parametrize("size", [(300, 200), (800, 600)])
def test_renders_without_overlap(size):
    """The view renders one frame with no overlapping rects, small and normal."""
    width, height = size
    # This exercises the same init -> update(RenderFrame) -> view lifecycle that
    # Plexi uses for a real app pane, then checks host-side layout geometry.
    with AppHarness(str(APP), width=width, height=height) as h:
        h.run(1)
        h.assert_no_overlap()


def test_snapshot(tmp_path):
    """Render a PNG snapshot of the first frame.

    Skips when the plexi binary is unavailable — snapshotting needs the host
    renderer, which is not present in a bare `uv run pytest` environment.
    """
    with AppHarness(str(APP), width=800, height=600) as h:
        h.run(1)
        try:
            h.save_snapshot(tmp_path / "snapshot.png")
        except RuntimeError as exc:
            pytest.skip(f"plexi binary not available for rendering: {exc}")


def test_tools_are_declared_and_dispatch():
    """init exposes the app.tools declarations; a ToolCall gets a ToolResult."""
    import sys

    sys.path.insert(0, str(APP_DIR))
    try:
        from app import tools as app_tools  # noqa: F401  (registers the tools)
        from plexi_sdk import tools

        names = {decl.name for decl in tools.declarations()}
        assert "demo.greet" in names
        assert isinstance(tools.expose(), ExposeTools)

        effects = tools.dispatch(ToolCall(
            call_id="c1", name="demo.greet", input_json=json.dumps({"name": "Ada"}), caller_id="test",
        ))
        assert effects is not None
        assert isinstance(effects[0], ToolResult)
        assert effects[0].output_json is not None
        assert json.loads(effects[0].output_json) == {"greeting": "Hello, Ada!"}
    finally:
        sys.path.remove(str(APP_DIR))
