schema_version = 1

[app]
id = "image-render-poc"
type = "app"
name = "Image Render Poc"
entry = "main.py"
version = "0.1.0"
description = "A Plexi app"
watch = true

[app.capabilities]
capabilities = ["fs.read"]

[launch]
layout_hint = { side = "right", split = 0.5 }
