schema_version = 1
reseed = "always"

[[app]]
id      = "logs"
source  = "local:logs"
version = "bundled"

[[app]]
id      = "stats"
source  = "local:stats"
version = "bundled"

[[app]]
id      = "todo"
source  = "local:todo"
version = "bundled"

[[app]]
id      = "calc"
source  = "local:calc"
version = "bundled"

[[app]]
id      = "permissions"
source  = "local:permissions"
version = "bundled"
