import type { ApplicationMenuItemConfig } from "electrobun/bun";
import { WORKSPACE_COMMANDS } from "../shared/commands.js";

export const createApplicationMenu = (): ApplicationMenuItemConfig[] => [
  {
    submenu: [
      { role: "hide" },
      { role: "hideOthers" },
      { role: "showAll" },
      { type: "separator" },
      { role: "quit" },
    ],
  },
  {
    label: "File",
    submenu: [
      { label: "New Node Right", action: "workspace:new-node-right", accelerator: "n" },
      { label: "New Node Down", action: "workspace:new-node-down", accelerator: "shift+n" },
      { type: "separator" },
      { label: "Split Right", action: "workspace:new-terminal-right", accelerator: "d" },
      { label: "Split Below", action: "workspace:new-terminal-down", accelerator: "shift+d" },
      { type: "separator" },
      { label: "Close Terminal", action: "workspace:close-terminal", accelerator: "w" },
      { label: "Close Window", role: "close" },
      { type: "separator" },
      { label: "Save Workspace", action: "workspace:save", accelerator: "s" },
    ],
  },
  {
    label: "Edit",
    submenu: [
      { role: "undo" },
      { role: "redo" },
      { type: "separator" },
      { role: "cut" },
      { role: "copy" },
      { role: "paste" },
      { role: "selectAll" },
    ],
  },
  {
    label: "View",
    submenu: [
      { label: "Toggle Sidebar", action: "workspace:toggle-sidebar", accelerator: "b" },
      { label: "Open Workspace Overview", action: "workspace:toggle-minimap" },
      { label: "Keyboard Reference", action: "workspace:show-shortcuts", accelerator: "/" },
      { type: "separator" },
      { label: "Zoom In", action: "workspace:zoom-in", accelerator: "=" },
      { label: "Zoom Out", action: "workspace:zoom-out", accelerator: "-" },
      { type: "separator" },
      { role: "toggleFullScreen" },
    ],
  },
  {
    label: "Workspace",
    submenu: [
      { label: "Focus Right", action: "workspace:focus-right" },
      { label: "Focus Left", action: "workspace:focus-left" },
      { label: "Focus Up", action: "workspace:focus-up" },
      { label: "Focus Down", action: "workspace:focus-down" },
      { label: "Jump Back", action: "workspace:jump-back" },
      { type: "separator" },
      { label: "Pane 1", action: `workspace:${WORKSPACE_COMMANDS.pane1}`, accelerator: "1" },
      { label: "Pane 2", action: `workspace:${WORKSPACE_COMMANDS.pane2}`, accelerator: "2" },
      { label: "Pane 3", action: `workspace:${WORKSPACE_COMMANDS.pane3}`, accelerator: "3" },
      { label: "Pane 4", action: `workspace:${WORKSPACE_COMMANDS.pane4}`, accelerator: "4" },
      { label: "Pane 5", action: `workspace:${WORKSPACE_COMMANDS.pane5}`, accelerator: "5" },
      { label: "Pane 6", action: `workspace:${WORKSPACE_COMMANDS.pane6}`, accelerator: "6" },
      { label: "Pane 7", action: `workspace:${WORKSPACE_COMMANDS.pane7}`, accelerator: "7" },
      { label: "Pane 8", action: `workspace:${WORKSPACE_COMMANDS.pane8}`, accelerator: "8" },
      { label: "Pane 9", action: `workspace:${WORKSPACE_COMMANDS.pane9}`, accelerator: "9" },
      { type: "separator" },
      { label: "Context 1", action: `workspace:${WORKSPACE_COMMANDS.context1}`, accelerator: "option+1" },
      { label: "Context 2", action: `workspace:${WORKSPACE_COMMANDS.context2}`, accelerator: "option+2" },
      { label: "Context 3", action: `workspace:${WORKSPACE_COMMANDS.context3}`, accelerator: "option+3" },
      { label: "Context 4", action: `workspace:${WORKSPACE_COMMANDS.context4}`, accelerator: "option+4" },
      { label: "Context 5", action: `workspace:${WORKSPACE_COMMANDS.context5}`, accelerator: "option+5" },
      { label: "Context 6", action: `workspace:${WORKSPACE_COMMANDS.context6}`, accelerator: "option+6" },
      { label: "Context 7", action: `workspace:${WORKSPACE_COMMANDS.context7}`, accelerator: "option+7" },
      { label: "Context 8", action: `workspace:${WORKSPACE_COMMANDS.context8}`, accelerator: "option+8" },
      { label: "Context 9", action: `workspace:${WORKSPACE_COMMANDS.context9}`, accelerator: "option+9" },
      { type: "separator" },
      { label: "Next Context", action: "workspace:next-context", accelerator: "]" },
      { label: "Previous Context", action: "workspace:previous-context", accelerator: "[" },
    ],
  },
  {
    label: "Window",
    submenu: [
      { role: "minimize" },
      { role: "zoom" },
      { role: "bringAllToFront" },
    ],
  },
  {
    label: "Help",
    submenu: [{ label: "Keyboard Reference", action: "workspace:show-shortcuts" }],
  },
];
