#!/usr/bin/env bash
# Usage: scripts/install.sh [channel]
# Derives channel from git branch (main→stable, alpha→alpha, beta→beta).
# Falls back to .channel file, then "stable". Must be run from the repo root.
set -euo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "install is macOS-only."
  exit 1
fi

_git_channel() {
  local branch
  branch="$(git branch --show-current 2>/dev/null || echo "")"
  case "$branch" in
    main)   echo "stable" ;;
    alpha)  echo "alpha" ;;
    beta)   echo "beta" ;;
    *)      cat .channel 2>/dev/null || echo "stable" ;;
  esac
}

channel="${1:-$(_git_channel)}"

if [[ "$channel" == "stable" ]]; then
  cap=""
  suffix=""
elif [[ "$channel" =~ ^pr-([0-9]+)$ ]]; then
  cap=" PR${BASH_REMATCH[1]}"
  suffix="-$channel"
else
  cap=" $(echo "$channel" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
  suffix="-$channel"
fi

display="Plexi${cap}"
bundle_id="com.ianjamesburke.plexi${suffix}"
app_src="target/release/bundle/osx/${display}.app"
app_dest="/Applications/${display}.app"
bin_dest="/usr/local/bin/plexi${suffix}"
profile_dir="$HOME/.plexi${suffix}"

# HACK: cargo-bundle reads bundle metadata from Cargo.toml directly with no
# env-var or CLI override. Patch the two bundle fields, build, then restore.
# Package `name` is left as "plexi" so Cargo.lock stays identical across branches.
if [[ -n "$suffix" ]]; then
  backup_dir="$(mktemp -d)"
  cp Cargo.toml "$backup_dir/Cargo.toml"
  cleanup() { cp "$backup_dir/Cargo.toml" Cargo.toml; rm -rf "$backup_dir"; }
  trap cleanup EXIT
  sed -i '' "s/name = \"Plexi[^\"]*\"/name = \"${display}\"/" Cargo.toml
  sed -i '' "s/identifier = \"com.ianjamesburke.plexi[^\"]*\"/identifier = \"${bundle_id}\"/" Cargo.toml
fi

cargo bundle --release

if [[ ! -d "$app_src" ]]; then
  echo "Error: bundle not found at $app_src"
  exit 1
fi

rm -rf "$app_dest"
cp -R "$app_src" "$app_dest"

# For non-stable channels, rename the binary inside the installed bundle from
# "plexi" to "plexi-<channel>" and update CFBundleExecutable to match.
# config_dir_name() detects the channel from current_exe() file_name(), so the
# binary name inside the bundle must contain the channel suffix or the app
# silently reads ~/.plexi/apps/ instead of ~/.plexi-<channel>/apps/.
if [[ -n "$suffix" ]]; then
  mv "$app_dest/Contents/MacOS/plexi" "$app_dest/Contents/MacOS/plexi${suffix}"
  /usr/bin/plutil -replace CFBundleExecutable -string "plexi${suffix}" "$app_dest/Contents/Info.plist"
fi

ln -sf "$app_dest/Contents/MacOS/plexi${suffix}" "$bin_dest"

# For non-PR channels (alpha, beta, stable), also update the bare `plexi`
# symlink so that `plexi open`, `plexi notify`, etc. always reach the correct
# running instance regardless of which channel was most recently installed.
# PR builds are excluded — they are ephemeral and should not capture the bare name.
if [[ ! "$channel" =~ ^pr- ]]; then
  ln -sf "$app_dest/Contents/MacOS/plexi${suffix}" /usr/local/bin/plexi
fi

# Install shell completions (non-PR builds only).
# Called after the binary symlink is in place at $bin_dest.
install_completions() {
  local binary="$1"

  # zsh: prefer Homebrew site-functions (already on fpath), else ~/.zfunc/
  if command -v brew &>/dev/null; then
    local brew_zsh_dir
    brew_zsh_dir="$(brew --prefix)/share/zsh/site-functions"
    if [[ -d "$brew_zsh_dir" ]]; then
      "$binary" completions zsh > "$brew_zsh_dir/_plexi"
      echo "Completions (zsh): $brew_zsh_dir/_plexi"
    fi
  else
    mkdir -p "$HOME/.zfunc"
    "$binary" completions zsh > "$HOME/.zfunc/_plexi"
    echo "Completions (zsh): ~/.zfunc/_plexi"
    echo "  note: add 'fpath=(~/.zfunc \$fpath)' to ~/.zshrc if not already present"
  fi

  # bash: ~/.bash_completion.d/
  mkdir -p "$HOME/.bash_completion.d"
  "$binary" completions bash > "$HOME/.bash_completion.d/plexi"
  echo "Completions (bash): ~/.bash_completion.d/plexi"

  # fish: only if fish is installed
  if [[ -d "$HOME/.config/fish" ]]; then
    mkdir -p "$HOME/.config/fish/completions"
    "$binary" completions fish > "$HOME/.config/fish/completions/plexi.fish"
    echo "Completions (fish): ~/.config/fish/completions/plexi.fish"
  fi
}

if [[ ! "$channel" =~ ^pr- ]]; then
  install_completions "$bin_dest"
fi

mkdir -p "$profile_dir/sdk" "$profile_dir/apps"
rm -rf "$profile_dir/sdk/plexi_sdk.py" "$profile_dir/sdk/plexi_sdk"
cp -R sdk/python/plexi_sdk "$profile_dir/sdk/plexi_sdk"
find "$profile_dir/sdk/plexi_sdk" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true
rsync -a --delete examples/ "$profile_dir/apps/"
find "$profile_dir/apps" -maxdepth 2 -name 'plexi_sdk.py' -delete 2>/dev/null || true
find "$profile_dir/apps" -name '*.py' -exec chmod +x {} \;

lsregister_bin="/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister"
if [[ -x "$lsregister_bin" ]]; then
  "$lsregister_bin" -f "$app_dest" 2>/dev/null || echo "note: lsregister -f failed"
fi
/System/Library/CoreServices/pbs -update 2>/dev/null || echo "note: pbs -update failed"

CONFIG="$profile_dir/config.toml"
if [ ! -f "$CONFIG" ]; then
  # Full config template — synced with CONFIG_TEMPLATE in src/config.rs.
  # To regenerate: python3 -c "import base64,sys; sys.stdout.write(base64.b64encode(open('scripts/default-config.toml','rb').read()).decode())"
  # (Once scripts/default-config.toml exists as the single source of truth — see issue #1118)
  echo "IyDilZTilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZcKIyDilZEgIFBsZXhpIENvbmZpZ3VyYXRpb24gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg4pWRCiMg4pWRICBDaGFuZ2VzIHRha2UgZWZmZWN0IG9uIG5leHQgbGF1bmNoLiAgICAgICAgICAgICAgICAgICAgICAgIOKVkQojIOKVmuKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVnQoKZm9udF9zaXplID0gMTQuMAoKIyDilIDilIAgVGhlbWUg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiMgUGljayBhIHByZXNldCBPUiBjdXN0b21pemUgaW5kaXZpZHVhbCBjb2xvcnMgYmVsb3cuCiMgUHJlc2V0czogY2F0cHB1Y2Npbi1tb2NoYSwgZHJhY3VsYSwgdG9reW8tbmlnaHQsIGdydXZib3gtZGFyaywgbm9yZCwgc29sYXJpemVkLWRhcmsKdGhlbWVfcHJlc2V0ID0gImNhdHBwdWNjaW4tbW9jaGEiCgojIOKUgOKUgCBDb25maXJtYXRpb24gRGlhbG9ncyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBjb25maXJtX3F1aXQgcmVxdWlyZXMgdHJpcGxlIENtZCtRIHRvIGV4aXQgKHNhZmVyIHRoYW4gYSBzaW5nbGUgcHJlc3MpLgojIGNvbmZpcm1fY2xvc2Ugc2hvd3MgYSBkaWFsb2cgYmVmb3JlIENtZCtXIGNsb3NlcyBhIHBhbmUuCmNvbmZpcm1fcXVpdCAgPSB0cnVlCmNvbmZpcm1fY2xvc2UgPSBmYWxzZQoKIyDilIDilIAgTm90aWZpY2F0aW9ucyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBUaGUgd29yay1hcmVhIG1vZGFsIGlzIHRoZSBvbmUgYW5kIG9ubHkgbm90aWZpY2F0aW9uIHN1cmZhY2UuCiMgQXBwcyBlbWl0IGBjdHgubm90aWZ5KC4uLilgLCBgY3R4Lm5vdGlmeV9jaG9pY2UoLi4uKWAsIG9yCiMgYGN0eC5ub3RpZnlfaW5wdXQoLi4uKWAgYW5kIHRoZSBtb2RhbCByZW5kZXJzIGVhY2gga2luZCB3aXRoCiMga2V5Ym9hcmQtZmlyc3QgbmF2aWdhdGlvbiAoRW50ZXIgY29uZmlybXMsIGovayBvciDihpHihpMgY3ljbGUKIyBvcHRpb25zLCAxLTkgZGlyZWN0LXNlbGVjdCwgRXNjIGNhbmNlbHMgd2hlbiBhbGxvd2VkKS4KW25vdGlmaWNhdGlvbnNdCiMgTWFzdGVyIHN3aXRjaC4gSWYgZmFsc2UsIG5vdGlmaWNhdGlvbnMgYXJlIHNpbGVudGx5IGRyb3BwZWQgYXQKIyBhcnJpdmFsIOKAlCBhcHBzIHN0aWxsIHNlbmQgdGhlbSwgdGhlIG1vZGFsIG5ldmVyIGFwcGVhcnMsIGFuZAojIHRoZSBxdWV1ZSBzdGF5cyBlbXB0eS4KIyBlbmFibGVkID0gdHJ1ZQoKIyBGb2N1cyBtb2RlLiBXaGVuIHRydWUsIE5PIG5vdGlmaWNhdGlvbiBhdXRvLXN1cmZhY2VzIHJlZ2FyZGxlc3Mgb2YKIyBwcmlvcml0eS4gRXZlcnl0aGluZyBxdWV1ZXMgc2lsZW50bHk7IG9wZW4gQ21kK1NoaWZ0K0EgdG8gcmV2aWV3LgojIGZvY3VzX21vZGUgPSBmYWxzZQoKIyBNaW5pbXVtIHByaW9yaXR5IHRoYXQgbWF5IGF1dG8tb3BlbiB0aGUgbW9kYWwuIE5vdGlmaWNhdGlvbnMgYmVsb3cKIyB0aGlzIHZhbHVlIHF1ZXVlIHNpbGVudGx5IChiYWRnZSB0aWNrcyBvbiB0aGUgdG9vbGJhciwgQ21kK1NoaWZ0K0EKIyByZXZlYWxzIHRoZW0pLiBBdCBvciBhYm92ZSBpdCwgYXJyaXZhbCBhdXRvLW9wZW5zIHRoZSBtb2RhbC4KIwojIFRpZXJzIChmcm9tIHBsZXhpX3Nkayk6CiMgICAwICAgPSBQUklPUklUWV9MT1cgICAgICAgKGJhY2tncm91bmQgaW5mbykKIyAgIDUwICA9IFBSSU9SSVRZX05PUk1BTCAgICAoc3RhbmRhcmQgY29uZmlybWF0aW9ucyDigJQgIm5vdGUgc2F2ZWQiKQojICAgMTAwID0gUFJJT1JJVFlfSElHSCAgICAgIChuZWVkcyBhdHRlbnRpb24gc29vbikKIyAgIDIwMCA9IFBSSU9SSVRZX0NSSVRJQ0FMICAoaW50ZXJydXB0LWxldmVsKQojCiMgRGVmYXVsdCA9IDEwMDogTk9STUFMIGFuZCBMT1cgcXVldWUgc2lsZW50bHksIEhJR0ggYW5kIENSSVRJQ0FMCiMgaW50ZXJydXB0LiBTZXQgdG8gMCB0byBhdXRvLW9wZW4gZXZlcnl0aGluZy4gU2V0IHRvIDIwMSB0byBtYXRjaAojIGZvY3VzX21vZGUgPSB0cnVlIChub3RoaW5nIGF1dG8tb3BlbnMpLgojIGludGVycnVwdF90aHJlc2hvbGQgPSAxMDAKCiMgRXNjIHZzIEVudGVyIG9uIHRoZSBtb2RhbDoKIyAgIEVudGVyIChvciBvcHRpb24tc2VsZWN0IC8gaW5wdXQtc3VibWl0KSA9IGFja25vd2xlZGdlLiBOb3RpZmljYXRpb24KIyAgICAgaXMgcmVtb3ZlZCBmcm9tIHRoZSBxdWV1ZSBhbmQgdGhlIGFwcCByZWNlaXZlcyBOb3RpZnlBY3Rpb24uCiMgICBFc2MgPSBkZWZlci4gTW9kYWwgY2xvc2VzIGJ1dCB0aGUgbm90aWZpY2F0aW9uIHN0YXlzIGluIHRoZSBxdWV1ZSDigJQKIyAgICAgb3BlbiBDbWQrU2hpZnQrQSBsYXRlciB0byBjb21lIGJhY2sgdG8gaXQuIE5vIE5vdGlmeUFjdGlvbiBkaXNwYXRjaGVkLgojICAgUmVxdWlyZWQgbm90aWZpY2F0aW9ucyAocmVxdWlyZWQgPSB0cnVlKSBjYW5ub3QgYmUgRXNjJ2QuCgpbdGhlbWVdCiMgUGljayBhIGZ1bGwgcHJlc2V0IHBhbGV0dGUgYnkgdW5jb21tZW50aW5nIG9uZSBibG9jayBiZWxvdywgb3Igc2V0CiMgaW5kaXZpZHVhbCBrZXlzIHRvIG92ZXJyaWRlIHRoZSBhY3RpdmUgdGhlbWVfcHJlc2V0IGFib3ZlLgojCiMgVG8gYnVpbGQgYSBjdXN0b20gdGhlbWUgZnJvbSBzY3JhdGNoLCBzZWUgYWxsIGF2YWlsYWJsZSBjb2xvciBuYW1lcwojIGFuZCB0aGVpciByb2xlcyBhdDogaHR0cHM6Ly9wbGV4aWFwcC5kZXYvZG9jcy9jb25maWcKIwojIOKUgOKUgCBjYXRwcHVjY2luLW1vY2hhIChkZWZhdWx0KSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBhY2NlbnQgICAgICAgICA9ICIjODliNGZhIgojIGJnX2Rhcmtlc3QgICAgID0gIiMxMTExMWIiCiMgYmdfc2lkZWJhciAgICAgPSAiIzE4MTgyNSIKIyBiZ190b29sYmFyICAgICA9ICIjMTgxODI1IgojIHRlcm1pbmFsX2JnICAgID0gIiMyOTJhNDQiCiMgYmdfaG92ZXIgICAgICAgPSAiIzJhMmEzYyIKIyBiZ19hY3RpdmUgICAgICA9ICIjMzEzMTQ0IgojIHRleHRfcHJpbWFyeSAgID0gIiNjZGQ2ZjQiCiMgdGV4dF9kaW0gICAgICAgPSAiIzZjNzA4NiIKIyB0ZXh0X3NlY3Rpb24gICA9ICIjNTg1YjcwIgojIGJvcmRlciAgICAgICAgID0gIiMyYTJhM2MiCiMgZm9yZWdyb3VuZCAgICAgPSAiI2U4ZTZlZCIKIyBiYWNrZ3JvdW5kICAgICA9ICIjMjkyYTQ0IgojIGJsYWNrICAgICAgICAgID0gIiMxMjEzMWUiCiMgcmVkICAgICAgICAgICAgPSAiI2RkNzc1NSIKIyBncmVlbiAgICAgICAgICA9ICIjMDRkYmI1IgojIHllbGxvdyAgICAgICAgID0gIiNmMmU3YjciCiMgYmx1ZSAgICAgICAgICAgPSAiIzdhYTVmZiIKIyBtYWdlbnRhICAgICAgICA9ICIjYmY5Y2Y5IgojIGN5YW4gICAgICAgICAgID0gIiM1NmQzYzIiCiMgd2hpdGUgICAgICAgICAgPSAiI2U0ZTNlOSIKIyBicmlnaHRfYmxhY2sgICA9ICIjNjY2Njk5IgojIGJyaWdodF9yZWQgICAgID0gIiNmZjkyY2QiCiMgYnJpZ2h0X2dyZWVuICAgPSAiIzAxZWFjMCIKIyBicmlnaHRfeWVsbG93ICA9ICIjZmZmY2E4IgojIGJyaWdodF9ibHVlICAgID0gIiM2OWMwZmEiCiMgYnJpZ2h0X21hZ2VudGEgPSAiI2MxN2ZmOCIKIyBicmlnaHRfY3lhbiAgICA9ICIjOGJmZGUxIgojIGJyaWdodF93aGl0ZSAgID0gIiNmNGYyZjkiCiMgYnJpZ2h0X2ZvcmVncm91bmQgPSAiI2Y0ZjJmOSIKCiMg4pSA4pSAIGRyYWN1bGEg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiMgYWNjZW50ICAgICAgICAgPSAiI2JkOTNmOSIKIyBiZ19kYXJrZXN0ICAgICA9ICIjMjgyYTM2IgojIGJnX3NpZGViYXIgICAgID0gIiMyMTIyMmMiCiMgYmdfdG9vbGJhciAgICAgPSAiIzIxMjIyYyIKIyB0ZXJtaW5hbF9iZyAgICA9ICIjMjgyYTM2IgojIGJnX2hvdmVyICAgICAgID0gIiMzNDM3NDYiCiMgYmdfYWN0aXZlICAgICAgPSAiIzNlNDE1NCIKIyB0ZXh0X3ByaW1hcnkgICA9ICIjZjhmOGYyIgojIHRleHRfZGltICAgICAgID0gIiM2MjcyYTQiCiMgdGV4dF9zZWN0aW9uICAgPSAiIzU0NTg3NiIKIyBib3JkZXIgICAgICAgICA9ICIjNDQ0NzVhIgojIGZvcmVncm91bmQgICAgID0gIiNmOGY4ZjIiCiMgYmFja2dyb3VuZCAgICAgPSAiIzI4MmEzNiIKIyBibGFjayAgICAgICAgICA9ICIjMjEyMjJjIgojIHJlZCAgICAgICAgICAgID0gIiNmZjU1NTUiCiMgZ3JlZW4gICAgICAgICAgPSAiIzUwZmE3YiIKIyB5ZWxsb3cgICAgICAgICA9ICIjZjFmYThjIgojIGJsdWUgICAgICAgICAgID0gIiM2MjcyYTQiCiMgbWFnZW50YSAgICAgICAgPSAiI2ZmNzljNiIKIyBjeWFuICAgICAgICAgICA9ICIjOGJlOWZkIgojIHdoaXRlICAgICAgICAgID0gIiNmOGY4ZjIiCiMgYnJpZ2h0X2JsYWNrICAgPSAiIzYyNzJhNCIKIyBicmlnaHRfcmVkICAgICA9ICIjZmY2ZTZlIgojIGJyaWdodF9ncmVlbiAgID0gIiM2OWZmOTQiCiMgYnJpZ2h0X3llbGxvdyAgPSAiI2ZmZmNhOCIKIyBicmlnaHRfYmx1ZSAgICA9ICIjZDZhY2ZmIgojIGJyaWdodF9tYWdlbnRhID0gIiNmZjkyZGYiCiMgYnJpZ2h0X2N5YW4gICAgPSAiI2E0ZmZmZiIKIyBicmlnaHRfd2hpdGUgICA9ICIjZmZmZmZmIgojIGJyaWdodF9mb3JlZ3JvdW5kID0gIiNmZmZmZmYiCgojIOKUgOKUgCB0b2t5by1uaWdodCDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBhY2NlbnQgICAgICAgICA9ICIjN2FhMmY3IgojIGJnX2Rhcmtlc3QgICAgID0gIiMxYTFiMjYiCiMgYmdfc2lkZWJhciAgICAgPSAiIzE2MTYxZSIKIyBiZ190b29sYmFyICAgICA9ICIjMTYxNjFlIgojIHRlcm1pbmFsX2JnICAgID0gIiMxYTFiMjYiCiMgYmdfaG92ZXIgICAgICAgPSAiIzIzMjQzMyIKIyBiZ19hY3RpdmUgICAgICA9ICIjMjkyZTQyIgojIHRleHRfcHJpbWFyeSAgID0gIiNhOWIxZDYiCiMgdGV4dF9kaW0gICAgICAgPSAiIzU2NWY4OSIKIyB0ZXh0X3NlY3Rpb24gICA9ICIjNDQ0YjZhIgojIGJvcmRlciAgICAgICAgID0gIiMyOTJlNDIiCiMgZm9yZWdyb3VuZCAgICAgPSAiI2E5YjFkNiIKIyBiYWNrZ3JvdW5kICAgICA9ICIjMWExYjI2IgojIGJsYWNrICAgICAgICAgID0gIiMxNjE2MWUiCiMgcmVkICAgICAgICAgICAgPSAiI2Y3NzY4ZSIKIyBncmVlbiAgICAgICAgICA9ICIjOWVjZTZhIgojIHllbGxvdyAgICAgICAgID0gIiNlMGFmNjgiCiMgYmx1ZSAgICAgICAgICAgPSAiIzdhYTJmNyIKIyBtYWdlbnRhICAgICAgICA9ICIjYmI5YWY3IgojIGN5YW4gICAgICAgICAgID0gIiM3ZGNmZmYiCiMgd2hpdGUgICAgICAgICAgPSAiI2E5YjFkNiIKIyBicmlnaHRfYmxhY2sgICA9ICIjNTY1Zjg5IgojIGJyaWdodF9yZWQgICAgID0gIiNmZjg5OWQiCiMgYnJpZ2h0X2dyZWVuICAgPSAiI2I1ZTg3YSIKIyBicmlnaHRfeWVsbG93ICA9ICIjZThjODdlIgojIGJyaWdodF9ibHVlICAgID0gIiM4ZGI4ZmYiCiMgYnJpZ2h0X21hZ2VudGEgPSAiI2M4YWRmZiIKIyBicmlnaHRfY3lhbiAgICA9ICIjOTBkOGZmIgojIGJyaWdodF93aGl0ZSAgID0gIiNjMGNhZjUiCiMgYnJpZ2h0X2ZvcmVncm91bmQgPSAiI2MwY2FmNSIKCiMg4pSA4pSAIGdydXZib3gtZGFyayDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBhY2NlbnQgICAgICAgICA9ICIjZmU4MDE5IgojIGJnX2Rhcmtlc3QgICAgID0gIiMxZDIwMjEiCiMgYmdfc2lkZWJhciAgICAgPSAiIzI4MjgyOCIKIyBiZ190b29sYmFyICAgICA9ICIjMjgyODI4IgojIHRlcm1pbmFsX2JnICAgID0gIiMyODI4MjgiCiMgYmdfaG92ZXIgICAgICAgPSAiIzNjMzgzNiIKIyBiZ19hY3RpdmUgICAgICA9ICIjNTA0OTQ1IgojIHRleHRfcHJpbWFyeSAgID0gIiNlYmRiYjIiCiMgdGV4dF9kaW0gICAgICAgPSAiIzkyODM3NCIKIyB0ZXh0X3NlY3Rpb24gICA9ICIjN2M2ZjY0IgojIGJvcmRlciAgICAgICAgID0gIiMzYzM4MzYiCiMgZm9yZWdyb3VuZCAgICAgPSAiI2ViZGJiMiIKIyBiYWNrZ3JvdW5kICAgICA9ICIjMjgyODI4IgojIGJsYWNrICAgICAgICAgID0gIiMxZDIwMjEiCiMgcmVkICAgICAgICAgICAgPSAiI2NjMjQxZCIKIyBncmVlbiAgICAgICAgICA9ICIjOTg5NzFhIgojIHllbGxvdyAgICAgICAgID0gIiNkNzk5MjEiCiMgYmx1ZSAgICAgICAgICAgPSAiIzQ1ODU4OCIKIyBtYWdlbnRhICAgICAgICA9ICIjYjE2Mjg2IgojIGN5YW4gICAgICAgICAgID0gIiM2ODlkNmEiCiMgd2hpdGUgICAgICAgICAgPSAiI2ViZGJiMiIKIyBicmlnaHRfYmxhY2sgICA9ICIjOTI4Mzc0IgojIGJyaWdodF9yZWQgICAgID0gIiNmYjQ5MzQiCiMgYnJpZ2h0X2dyZWVuICAgPSAiI2I4YmIyNiIKIyBicmlnaHRfeWVsbG93ICA9ICIjZmFiZDJmIgojIGJyaWdodF9ibHVlICAgID0gIiM4M2E1OTgiCiMgYnJpZ2h0X21hZ2VudGEgPSAiI2QzODY5YiIKIyBicmlnaHRfY3lhbiAgICA9ICIjOGVjMDdjIgojIGJyaWdodF93aGl0ZSAgID0gIiNmYmYxYzciCiMgYnJpZ2h0X2ZvcmVncm91bmQgPSAiI2ZiZjFjNyIKCiMg4pSA4pSAIG5vcmQg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiMgYWNjZW50ICAgICAgICAgPSAiIzg4YzBkMCIKIyBiZ19kYXJrZXN0ICAgICA9ICIjMmUzNDQwIgojIGJnX3NpZGViYXIgICAgID0gIiMzYjQyNTIiCiMgYmdfdG9vbGJhciAgICAgPSAiIzNiNDI1MiIKIyB0ZXJtaW5hbF9iZyAgICA9ICIjMmUzNDQwIgojIGJnX2hvdmVyICAgICAgID0gIiM0MzRjNWUiCiMgYmdfYWN0aXZlICAgICAgPSAiIzRjNTY2YSIKIyB0ZXh0X3ByaW1hcnkgICA9ICIjZWNlZmY0IgojIHRleHRfZGltICAgICAgID0gIiM0YzU2NmEiCiMgdGV4dF9zZWN0aW9uICAgPSAiIzQzNGM1ZSIKIyBib3JkZXIgICAgICAgICA9ICIjM2I0MjUyIgojIGZvcmVncm91bmQgICAgID0gIiNlY2VmZjQiCiMgYmFja2dyb3VuZCAgICAgPSAiIzJlMzQ0MCIKIyBibGFjayAgICAgICAgICA9ICIjM2I0MjUyIgojIHJlZCAgICAgICAgICAgID0gIiNiZjYxNmEiCiMgZ3JlZW4gICAgICAgICAgPSAiI2EzYmU4YyIKIyB5ZWxsb3cgICAgICAgICA9ICIjZWJjYjhiIgojIGJsdWUgICAgICAgICAgID0gIiM4MWExYzEiCiMgbWFnZW50YSAgICAgICAgPSAiI2I0OGVhZCIKIyBjeWFuICAgICAgICAgICA9ICIjODhjMGQwIgojIHdoaXRlICAgICAgICAgID0gIiNlY2VmZjQiCiMgYnJpZ2h0X2JsYWNrICAgPSAiIzRjNTY2YSIKIyBicmlnaHRfcmVkICAgICA9ICIjZDA4NzcwIgojIGJyaWdodF9ncmVlbiAgID0gIiNhM2JlOGMiCiMgYnJpZ2h0X3llbGxvdyAgPSAiI2ViY2I4YiIKIyBicmlnaHRfYmx1ZSAgICA9ICIjODFhMWMxIgojIGJyaWdodF9tYWdlbnRhID0gIiNiNDhlYWQiCiMgYnJpZ2h0X2N5YW4gICAgPSAiIzhmYmNiYiIKIyBicmlnaHRfd2hpdGUgICA9ICIjZTVlOWYwIgojIGJyaWdodF9mb3JlZ3JvdW5kID0gIiNlNWU5ZjAiCgojIOKUgOKUgCBzb2xhcml6ZWQtZGFyayDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBhY2NlbnQgICAgICAgICA9ICIjMjY4YmQyIgojIGJnX2Rhcmtlc3QgICAgID0gIiMwMDJiMzYiCiMgYmdfc2lkZWJhciAgICAgPSAiIzA3MzY0MiIKIyBiZ190b29sYmFyICAgICA9ICIjMDczNjQyIgojIHRlcm1pbmFsX2JnICAgID0gIiMwMDJiMzYiCiMgYmdfaG92ZXIgICAgICAgPSAiIzBhNDA1MCIKIyBiZ19hY3RpdmUgICAgICA9ICIjMTI0ZDVlIgojIHRleHRfcHJpbWFyeSAgID0gIiM4Mzk0OTYiCiMgdGV4dF9kaW0gICAgICAgPSAiIzU4NmU3NSIKIyB0ZXh0X3NlY3Rpb24gICA9ICIjNGQ2MjY5IgojIGJvcmRlciAgICAgICAgID0gIiMwNzM2NDIiCiMgZm9yZWdyb3VuZCAgICAgPSAiIzgzOTQ5NiIKIyBiYWNrZ3JvdW5kICAgICA9ICIjMDAyYjM2IgojIGJsYWNrICAgICAgICAgID0gIiMwNzM2NDIiCiMgcmVkICAgICAgICAgICAgPSAiI2RjMzIyZiIKIyBncmVlbiAgICAgICAgICA9ICIjODU5OTAwIgojIHllbGxvdyAgICAgICAgID0gIiNiNTg5MDAiCiMgYmx1ZSAgICAgICAgICAgPSAiIzI2OGJkMiIKIyBtYWdlbnRhICAgICAgICA9ICIjZDMzNjgyIgojIGN5YW4gICAgICAgICAgID0gIiMyYWExOTgiCiMgd2hpdGUgICAgICAgICAgPSAiI2VlZThkNSIKIyBicmlnaHRfYmxhY2sgICA9ICIjNTg2ZTc1IgojIGJyaWdodF9yZWQgICAgID0gIiNjYjRiMTYiCiMgYnJpZ2h0X2dyZWVuICAgPSAiIzg1OTkwMCIKIyBicmlnaHRfeWVsbG93ICA9ICIjYjU4OTAwIgojIGJyaWdodF9ibHVlICAgID0gIiMyNjhiZDIiCiMgYnJpZ2h0X21hZ2VudGEgPSAiIzZjNzFjNCIKIyBicmlnaHRfY3lhbiAgICA9ICIjMmFhMTk4IgojIGJyaWdodF93aGl0ZSAgID0gIiNmZGY2ZTMiCiMgYnJpZ2h0X2ZvcmVncm91bmQgPSAiI2ZkZjZlMyIKCiMg4pSA4pSAIFBsZXhpIEFJIOKAlCBicm9rZXJlZCBMTE0gY2FsbHMgKGBhaS5xdWVyeWAgY2FwYWJpbGl0eSkg4pSA4pSA4pSA4pSA4pSACiMgQXBwcyB0aGF0IGRlY2xhcmUgYGFpLnF1ZXJ5YCBpbiB0aGVpciBtYW5pZmVzdCBjYW4gY2FsbCB0aWVyLXJvdXRlZAojIExMTSBtb2RlbHMgdGhyb3VnaCB0aGUgaG9zdCBicm9rZXIuIFR3byBiYWNrZW5kcyBhcmUgc3VwcG9ydGVkOgojICJvcGVucm91dGVyIiAoZGVmYXVsdCwgY2xvdWQpIGFuZCAib2xsYW1hIiAobG9jYWwpLgojCiMgT3BlblJvdXRlciAoZGVmYXVsdCk6CiMgICBFeHBvcnQgeW91ciBrZXkgaW4gfi8uenByb2ZpbGUgb3Igfi8uenNocmM6CiMgICAgIGV4cG9ydCBPUEVOUk9VVEVSX0FQSV9LRVk9InNrLW9yLS4uLiIKIwpbYWldCmJhY2tlbmQgPSAib3BlbnJvdXRlciIKClthaS5vcGVucm91dGVyXQphcGlfa2V5X2VudiAgPSAiT1BFTlJPVVRFUl9BUElfS0VZIgptb2RlbF9sb3cgICAgPSAiZ29vZ2xlL2dlbWluaS0yLjAtZmxhc2gtMDAxIgptb2RlbF9tZWRpdW0gPSAiYW50aHJvcGljL2NsYXVkZS1zb25uZXQtNC02Igptb2RlbF9oaWdoICAgPSAiYW50aHJvcGljL2NsYXVkZS1vcHVzLTQtNyIKCiMgT2xsYW1hIChsb2NhbCk6CiMgW2FpXQojIGJhY2tlbmQgPSAib2xsYW1hIgojCiMgW2FpLm9sbGFtYV0KIyBob3N0ICAgICAgICAgPSAiaHR0cDovL2xvY2FsaG9zdDoxMTQzNCIKIyBtb2RlbF9sb3cgICAgPSAibGxhbWEzLjI6M2IiCiMgbW9kZWxfbWVkaXVtID0gImxsYW1hMy4zOjcwYiIKIyBtb2RlbF9oaWdoICAgPSAicXdxOjMyYiIKCiMg4pSA4pSAIEV4cGVyaW1lbnRhbCBGZWF0dXJlcyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBGbGlwIGFueSBmbGFnIHRvIHRydWUgYW5kIHJlc3RhcnQgdG8gZW5hYmxlLgpbYmV0YV0KIyBjcnQgICA9IGZhbHNlICAgICMgUmV0cm8gQ1JUIHNjYW5saW5lcyArIGdyZWVuIHBob3NwaG9yIHRpbnQKIyBnaG9zdCA9IGZhbHNlICAgICMgVW5mb2N1c2VkIHBhbmVzIHJlbmRlciBhdCByZWR1Y2VkIG9wYWNpdHkKCiMg4pSA4pSAIExvZ2dpbmcg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiMgW2xvZ10KIyBsZXZlbCA9ICJpbmZvIiAgICAgICAgICAjIGVycm9yIHwgd2FybiB8IGluZm8gfCBkZWJ1ZyAgKGRlZmF1bHQ6IGluZm8pCiMgcmV0ZW50aW9uX2RheXMgPSAzMCAgICAgIyBkYXlzIHRvIGtlZXAgZGF0ZWQgbG9nIGFyY2hpdmVzIChkZWZhdWx0OiAzMCkKCiMg4pSA4pSAIEtleWJpbmRpbmdzIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIE92ZXJyaWRlIGFueSBkZWZhdWx0IGtleWJpbmRpbmcuIEZvcm1hdDogIm1vZGlmaWVyK2tleSIgKGNhc2UtaW5zZW5zaXRpdmUpLgojIE1vZGlmaWVyczogY21kLCBzaGlmdCwgY3RybCwgYWx0IChhbGlhc2VzOiBjb21tYW5kLCBjb250cm9sLCBvcHQsIG9wdGlvbikuCiMgS2V5czogYS16LCAwLTksIGVudGVyLCBlc2NhcGUsIHRhYiwgc3BhY2UsIGJhY2tzcGFjZSwgdXAsIGRvd24sCiMgICBsZWZ0LCByaWdodCwgb3Blbl9icmFja2V0LCBjbG9zZV9icmFja2V0LCBiYWNrc2xhc2gsIHNsYXNoLCBjb21tYSwKIyAgIHBlcmlvZCwgZXF1YWxzLCBtaW51cy4KIyBVbmtub3duIGtleXMgb3IgY29uZmxpY3Rpbmcgb3ZlcnJpZGVzIGxvZyBhbiBlcnJvciBhdCBzdGFydHVwLgojIFtrZXliaW5kaW5nc10KIyBxdWl0ICAgICAgICAgICAgICAgICAgICA9ICJjbWQrcSIKIyBjbG9zZV9wYW5lICAgICAgICAgICAgICA9ICJjbWQrdyIKIyB0b2dnbGVfY29tbWFuZF9wYWxldHRlICA9ICJjbWQrcCIKIyBzcGxpdF9ob3Jpem9udGFsICAgICAgICA9ICJjbWQrZCIKIyBzcGxpdF92ZXJ0aWNhbCAgICAgICAgICA9ICJjbWQrc2hpZnQrZCIKIyBzcGxpdF9yaWdodCAgICAgICAgICAgICA9ICJjbWQrYmFja3NsYXNoIgojIHNwbGl0X2Rvd24gICAgICAgICAgICAgID0gImNtZCtzaGlmdCtiYWNrc2xhc2giCiMgbmF2aWdhdGVfbGVmdCAgICAgICAgICAgPSAiY21kK2giCiMgbmF2aWdhdGVfZG93biAgICAgICAgICAgPSAiY21kK2oiCiMgbmF2aWdhdGVfdXAgICAgICAgICAgICAgPSAiY21kK2siCiMgbmF2aWdhdGVfcmlnaHQgICAgICAgICAgPSAiY21kK2wiCiMgc3dhcF9wYW5lX2xlZnQgICAgICAgICAgPSAiY21kK2N0cmwraCIKIyBzd2FwX3BhbmVfZG93biAgICAgICAgICA9ICJjbWQrY3RybCtqIgojIHN3YXBfcGFuZV91cCAgICAgICAgICAgID0gImNtZCtjdHJsK2siCiMgc3dhcF9wYW5lX3JpZ2h0ICAgICAgICAgPSAiY21kK2N0cmwrbCIKIyBuZXdfdGFiICAgICAgICAgICAgICAgICA9ICJjbWQrdCIKIyBuZXh0X3RhYiAgICAgICAgICAgICAgICA9ICJjbWQrc2hpZnQrbCIKIyBwcmV2X3RhYiAgICAgICAgICAgICAgICA9ICJjbWQrc2hpZnQraCIKIyBmaXJzdF90YWIgICAgICAgICAgICAgICA9ICJjbWQrc2hpZnQrayIKIyBsYXN0X3RhYiAgICAgICAgICAgICAgICA9ICJjbWQrc2hpZnQraiIKIyBuYXZfYmFjayAgICAgICAgICAgICAgICA9ICJjbWQrb3Blbl9icmFja2V0IgojIHRvZ2dsZV9zaWRlYmFyICAgICAgICAgID0gImNtZCtiIgojIHRvZ2dsZV96b29tICAgICAgICAgICAgID0gImNtZCtlbnRlciIKIyB0b2dnbGVfc2hvcnRjdXRzICAgICAgICA9ICJjbWQrc2xhc2giCiMgcmVuYW1lX3BhbmUgICAgICAgICAgICAgPSAiY21kK3IiCiMgcmVuYW1lX2NvbnRleHQgICAgICAgICAgPSAiY21kK3NoaWZ0K3IiCiMgbmV3X3BhZ2VfcmlnaHQgICAgICAgICAgPSAiY21kK24iCiMgbmV3X2NvbnRleHQgICAgICAgICAgICAgPSAiY21kK3NoaWZ0K24iCiMgdG9nZ2xlX21pbmltYXAgICAgICAgICAgPSAiY21kK3NoaWZ0K20iCiMgc2Nyb2xsX3VwICAgICAgICAgICAgICAgPSAiY21kK3VwIgojIHNjcm9sbF9kb3duICAgICAgICAgICAgID0gImNtZCtkb3duIgojIGluY3JlYXNlX2ZvbnRfc2l6ZSAgICAgID0gImNtZCtlcXVhbHMiCiMgZGVjcmVhc2VfZm9udF9zaXplICAgICAgPSAiY21kK21pbnVzIgojIG9wZW5fZmlsZV9icm93c2VyICAgICAgID0gImNtZCtlIgojIG9wZW5fcXVpY2tfbm90ZSAgICAgICAgID0gImNtZCswIgojIG9wZW5fY29uZmlnICAgICAgICAgICAgID0gImNtZCtjb21tYSIKIyByZWxvYWRfY29uZmlnICAgICAgICAgICA9ICJjbWQrc2hpZnQrY29tbWEiCiMgb3Blbl9zZWNyZXRzX21hbmFnZXIgICAgPSAiY21kK3NoaWZ0K3MiCiMgZm9yY2VfcmVsb2FkX2FwcCAgICAgICAgPSAiY21kK2FsdCtyIgojIHRvZ2dsZV9ub3RpZmljYXRpb25fbW9kYWwgPSAiY21kK3NoaWZ0K2EiCgojIOKUgOKUgCBRdWljayBOb3RlIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIENtZCswIG9wZW5zIGEgY29tcG9zZSBtb2RhbC4gRW50ZXIgYWR2YW5jZXMgdG8gdGhlIGRlc3RpbmF0aW9uCiMgcGlja2VyLiBQcmVzcyBhIGRpZ2l0IGtleSB0byByb3V0ZSBpbnN0YW50bHkg4oCUIG5vIEVudGVyIG5lZWRlZC4KIyBTdWJtZW51IGVudHJpZXMgKG9wdGlvbnMgPSBbLi4uXSkgZXhwYW5kIG9uIHRoZSBwYXJlbnQga2V5cHJlc3MuCiMgRGVzdGluYXRpb24gMCAoZ2xvYmFsIGJhY2tsb2cg4oaSIH4vLnBsZXhpL2JhY2tsb2cpIGlzIGFsd2F5cwojIGF2YWlsYWJsZSByZWdhcmRsZXNzIG9mIGNvbmZpZy4KIwojIFRva2VucyBpbiBgY29tbWFuZGA6ICB7bm90ZX0gPSBub3RlIHRleHQgKHNoZWxsLWVzY2FwZWQpCiMgICAgICAgICAgICAgICAgICAgICAgICB7Y3dkfSAgPSBmb2N1c2VkIHBhbmUgZGlyZWN0b3J5CiMKIyBbW3F1aWNrX25vdGUuZGVzdGluYXRpb25zXV0KIyBrZXkgICAgID0gMQojIGxhYmVsICAgPSAiQmFja2xvZyIKIyB0eXBlICAgID0gImJhY2tsb2ciCiMgcGF0aCAgICA9ICJ+Ly5wbGV4aS9iYWNrbG9nIgojCiMgW1txdWlja19ub3RlLmRlc3RpbmF0aW9uc11dCiMga2V5ICAgICA9IDIKIyBsYWJlbCAgID0gIkFzayBDbGF1ZGUiCiMgdHlwZSAgICA9ICJwYW5lIgojIGNvbW1hbmQgPSAiY2xhdWRlIC1wIHtub3RlfSIKIyBwb3NpdGlvbiA9ICJjb250ZXh0LWVuZCIKIwojIFtbcXVpY2tfbm90ZS5kZXN0aW5hdGlvbnNdXQojIGtleSAgICAgPSAzCiMgbGFiZWwgICA9ICJHaXRIdWIgaXNzdWUiCiMgb3B0aW9ucyA9IFsKIyAgIHsga2V5ID0gMSwgbGFiZWwgPSAiQnVnIHJlcG9ydCIsICAgICAgIGNvbW1hbmQgPSAiY2Qge2N3ZH0gJiYgZ2ggaXNzdWUgY3JlYXRlIC0tbGFiZWwgYnVnIC0tdGl0bGUge25vdGV9IC0tYm9keSAnJyIgfSwKIyAgIHsga2V5ID0gMiwgbGFiZWwgPSAiRmVhdHVyZSByZXF1ZXN0IiwgIGNvbW1hbmQgPSAiY2Qge2N3ZH0gJiYgZ2ggaXNzdWUgY3JlYXRlIC0tbGFiZWwgZW5oYW5jZW1lbnQgLS10aXRsZSB7bm90ZX0gLS1ib2R5ICcnIiB9LAojICAgeyBrZXkgPSAzLCBsYWJlbCA9ICJEcmFmdCAobm8gbGFiZWwpIiwgY29tbWFuZCA9ICJjZCB7Y3dkfSAmJiBnaCBpc3N1ZSBjcmVhdGUgLS10aXRsZSB7bm90ZX0gLS1ib2R5ICcnIC0tZHJhZnQiIH0sCiMgXQo=" | base64 --decode > "$CONFIG"
  echo "config: created default config at $CONFIG — set OPENROUTER_API_KEY in your shell profile"
fi

# Ensure all required top-level config sections are present (additive-only migration).
# Sections: [notifications] [theme] [ai] [beta]
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"$SCRIPT_DIR/migrate-config.sh" "$CONFIG" "[notifications]" "[theme]" "[ai]" "[beta]"

echo "Installed $app_dest"
echo "CLI: $bin_dest"
echo "Config dir: $profile_dir/"
echo "Apps: $(ls "$profile_dir/apps" | wc -l | tr -d ' ') synced from examples/"
