function byId(id) {
  return document.getElementById(id);
}

export const dom = {
  appShell: byId("app-shell"),
  sidebar: byId("sidebar"),
  stage: byId("stage"),
  focusShell: byId("focus-shell"),
  overviewShell: byId("overview-shell"),
  emptyShell: byId("empty-shell"),
  terminalMount: byId("terminal-mount"),
  overviewCanvas: byId("overview-canvas"),
  minimap: byId("minimap"),
  minimapGrid: byId("minimap-grid"),
  minimapSize: byId("minimap-size"),
  shortcutsOverlay: byId("shortcuts-overlay"),
  contextList: byId("context-list"),
  newContextButton: byId("new-context"),
  saveWorkspaceButton: byId("save-workspace"),
  toolbarSaveWorkspaceButton: byId("toolbar-save-workspace"),
  toggleWorkspaceJsonButton: byId("toggle-workspace-json"),
  toolbarToggleJsonButton: byId("toolbar-toggle-json"),
  focusTitle: byId("focus-title"),
  focusPath: byId("focus-path"),
  focusPosition: byId("focus-position"),
  toolbarContext: byId("toolbar-context"),
  workspaceStorageLabel: byId("workspace-storage-label"),
  workspacePath: byId("workspace-path"),
  workspaceJsonShell: byId("workspace-json-shell"),
  workspaceJson: byId("workspace-json"),
  engineLabel: byId("engine-label"),
  modeLabel: byId("mode-label"),
  toastLayer: byId("toast-layer"),
  contextModal: byId("context-modal"),
  contextForm: byId("context-form"),
  contextModalTitle: byId("context-modal-title"),
  contextNameInput: byId("context-name-input"),
  contextCancelButton: byId("context-cancel"),
  contextCloseButton: byId("context-close"),
  contextSubmitButton: byId("context-submit"),
};
