function byId(id) {
  return document.getElementById(id);
}

export const dom = {
  appShell: byId("app-shell"),
  sidebar: byId("sidebar"),
  stage: byId("stage"),
  focusShell: byId("focus-shell"),
  overviewShell: byId("overview-shell"),
  emptyShell: byId("empty-shell"),
  terminalMount: byId("terminal-mount"),
  overviewCanvas: byId("overview-canvas"),
  minimap: byId("minimap"),
  minimapGrid: byId("minimap-grid"),
  minimapSize: byId("minimap-size"),
  shortcutsOverlay: byId("shortcuts-overlay"),
  contextList: byId("context-list"),
  newContextButton: byId("new-context"),
  focusTitle: byId("focus-title"),
  focusPath: byId("focus-path"),
  focusRightSlot: byId("focus-right-slot"),
  focusBottomSlot: byId("focus-bottom-slot"),
  overviewTitle: byId("overview-title"),
  overviewBody: byId("overview-body"),
  workspaceStorageLabel: byId("workspace-storage-label"),
  engineLabel: byId("engine-label"),
  toastLayer: byId("toast-layer"),
  contextModal: byId("context-modal"),
  contextForm: byId("context-form"),
  contextModalTitle: byId("context-modal-title"),
  contextNameInput: byId("context-name-input"),
  contextCancelButton: byId("context-cancel"),
  contextCloseButton: byId("context-close"),
  contextSubmitButton: byId("context-submit"),
};
