import { compileKeybinds } from "../shared/keybinds.js";

const platformName =
  globalThis.navigator?.userAgentData?.platform ||
  globalThis.navigator?.platform ||
  globalThis.navigator?.userAgent ||
  (process.platform === "darwin" ? "Mac" : process.platform);
const isMacOS = /\bMac/i.test(platformName);

const APP_KEYBIND_SPECS = isMacOS
  ? [
    "super+n=new_node_right",
    "ctrl+n=new_node_right",
    "super+shift+n=new_node_down",
    "ctrl+shift+n=new_node_down",
    "super+d=new_terminal_right",
    "ctrl+d=new_terminal_right",
    "super+shift+d=new_terminal_down",
    "ctrl+shift+d=new_terminal_down",
    "super+w=close_terminal",
    "ctrl+w=close_terminal",
    "super+q=quit_application",
    "ctrl+q=quit_application",
    "super+s=save_workspace",
    "ctrl+s=save_workspace",
    "super+b=toggle_sidebar",
    "ctrl+b=toggle_sidebar",
    "super+m=toggle_minimap",
    "ctrl+m=toggle_minimap",
    "super+/=toggle_shortcuts",
    "ctrl+/=toggle_shortcuts",
    "super+equal=zoom_in",
    "super+minus=zoom_out",
    "ctrl+equal=zoom_in",
    "ctrl+minus=zoom_out",
    "super+left=focus_left",
    "ctrl+left=focus_left",
    "super+h=focus_left",
    "ctrl+h=focus_left",
    "super+right=focus_right",
    "ctrl+right=focus_right",
    "super+l=focus_right",
    "ctrl+l=focus_right",
    "super+up=focus_up",
    "ctrl+up=focus_up",
    "super+k=focus_up",
    "ctrl+k=focus_up",
    "super+down=focus_down",
    "ctrl+down=focus_down",
    "super+j=focus_down",
    "ctrl+j=focus_down",
    "super+1=pane_1",
    "ctrl+1=pane_1",
    "super+2=pane_2",
    "ctrl+2=pane_2",
    "super+3=pane_3",
    "ctrl+3=pane_3",
    "super+4=pane_4",
    "ctrl+4=pane_4",
    "super+5=pane_5",
    "ctrl+5=pane_5",
    "super+6=pane_6",
    "ctrl+6=pane_6",
    "super+7=pane_7",
    "ctrl+7=pane_7",
    "super+8=pane_8",
    "ctrl+8=pane_8",
    "super+9=pane_9",
    "ctrl+9=pane_9",
    "super+[=previous_context",
    "ctrl+[=previous_context",
    "super+]=next_context",
    "ctrl+]=next_context",
    "super+alt+1=context_1",
    "ctrl+alt+1=context_1",
    "super+alt+2=context_2",
    "ctrl+alt+2=context_2",
    "super+alt+3=context_3",
    "ctrl+alt+3=context_3",
    "super+alt+4=context_4",
    "ctrl+alt+4=context_4",
    "super+alt+5=context_5",
    "ctrl+alt+5=context_5",
    "super+alt+6=context_6",
    "ctrl+alt+6=context_6",
    "super+alt+7=context_7",
    "ctrl+alt+7=context_7",
    "super+alt+8=context_8",
    "ctrl+alt+8=context_8",
    "super+alt+9=context_9",
    "ctrl+alt+9=context_9",
  ]
  : [
    "ctrl+n=new_node_right",
    "ctrl+shift+n=new_node_down",
    "ctrl+d=new_terminal_right",
    "ctrl+shift+d=new_terminal_down",
    "ctrl+w=close_terminal",
    "ctrl+q=quit_application",
    "ctrl+s=save_workspace",
    "ctrl+b=toggle_sidebar",
    "ctrl+m=toggle_minimap",
    "ctrl+/=toggle_shortcuts",
    "ctrl+equal=zoom_in",
    "ctrl+minus=zoom_out",
    "ctrl+left=focus_left",
    "ctrl+h=focus_left",
    "ctrl+right=focus_right",
    "ctrl+l=focus_right",
    "ctrl+up=focus_up",
    "ctrl+k=focus_up",
    "ctrl+down=focus_down",
    "ctrl+j=focus_down",
    "ctrl+1=pane_1",
    "ctrl+2=pane_2",
    "ctrl+3=pane_3",
    "ctrl+4=pane_4",
    "ctrl+5=pane_5",
    "ctrl+6=pane_6",
    "ctrl+7=pane_7",
    "ctrl+8=pane_8",
    "ctrl+9=pane_9",
    "ctrl+[=previous_context",
    "ctrl+]=next_context",
    "ctrl+alt+1=context_1",
    "ctrl+alt+2=context_2",
    "ctrl+alt+3=context_3",
    "ctrl+alt+4=context_4",
    "ctrl+alt+5=context_5",
    "ctrl+alt+6=context_6",
    "ctrl+alt+7=context_7",
    "ctrl+alt+8=context_8",
    "ctrl+alt+9=context_9",
  ];

const TERMINAL_KEYBIND_SPECS = isMacOS
  ? [
    "performable:super+c=copy_to_clipboard",
    "super+v=paste_from_clipboard",
  ]
  : [
    "performable:ctrl+c=copy_to_clipboard",
    "ctrl+v=paste_from_clipboard",
  ];

export const APP_KEYBINDS = compileKeybinds(APP_KEYBIND_SPECS);
export const TERMINAL_KEYBINDS = compileKeybinds(TERMINAL_KEYBIND_SPECS);
