name: Build & Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      PLEXI_AUDIO: "mock://"
      PLEXI_VIDEO: "mock://"
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Cargo build
        run: cargo build

      - name: Cargo test
        run: cargo test --bin plexi
